/*
 * module function declaration for library fmpcwmlib header (autogenerated)
 */

#include "fmpcwmlib_module.h"

int fmpcwmlib_mod_init(ubx_node_info_t* ni)
{
  int ret;
  ret=fmpc_world_model_mod_init(ni);
  if(ret!=0)
    goto out;

out:
   return ret;
}

void fmpcwmlib_mod_cleanup(ubx_node_info_t* ni)
{
  fmpc_world_model_mod_cleanup(ni);
}

